# Generated by Django 4.2.30 on 2026-06-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
